// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDwCvAG9cafs3anOr72m8KJfjM7_HS_3Y',
    appId: '1:19640108832:web:888756d8ae37dc4f5cb945',
    messagingSenderId: '19640108832',
    projectId: 'viajuntos-397806',
    authDomain: 'viajuntos-397806.firebaseapp.com',
    storageBucket: 'viajuntos-397806.appspot.com',
    measurementId: 'G-9CJZ5BZCBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojDgmyDQzrb7YJ-4HE4pWSWPdjymHQLg',
    appId: '1:19640108832:android:5208c60ec17e12765cb945',
    messagingSenderId: '19640108832',
    projectId: 'viajuntos-397806',
    storageBucket: 'viajuntos-397806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNFsH0_hF7KMg3jKWcpEno1bfJAdMhr8w',
    appId: '1:19640108832:ios:56443834fe73ceb65cb945',
    messagingSenderId: '19640108832',
    projectId: 'viajuntos-397806',
    storageBucket: 'viajuntos-397806.appspot.com',
    androidClientId: '19640108832-r6foed3s5t032e4vo5re7avpakkvsesb.apps.googleusercontent.com',
    iosClientId: '19640108832-shq877iqpeoj189q6tedlfgvikjfbbdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.viajuntos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNFsH0_hF7KMg3jKWcpEno1bfJAdMhr8w',
    appId: '1:19640108832:ios:0a6635a22a4bd57f5cb945',
    messagingSenderId: '19640108832',
    projectId: 'viajuntos-397806',
    storageBucket: 'viajuntos-397806.appspot.com',
    androidClientId: '19640108832-r6foed3s5t032e4vo5re7avpakkvsesb.apps.googleusercontent.com',
    iosClientId: '19640108832-thor23s62gbbbjcp50e9kjdtrr1pknjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.viajuntos.RunnerTests',
  );
}
